{% set python_min = "3.11" %}
{% set name = "fhaviary" %}
{% set version = "0.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhaviary-{{ version }}.tar.gz
  sha256: e1bd80036154e7dd6e5771d7f0f3d39c2f2d05e8b885eade8b930ffd1dc980fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - httpx-aiohttp
    - python >={{ python_min }}
    - docstring_parser >=0.16
    - httpx
    - pydantic >=2.0,<3.dev0

test:
  imports:
    - aviary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/fhaviary/
  summary: Gymnasium framework for training language model agents on constructive tasks
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
