{% set name = "fhaviary" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhaviary-{{ version }}.tar.gz
  sha256: c38a4c9216678e2e22dc3ef18b6ef0d1380c055a94dcca0cfb9d4e17b2849735

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.11
    - docstring_parser >=0.16
    - httpx
    - pydantic >=2.0,<3.dev0

test:
  imports:
    - aviary
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/fhaviary/
  summary: Gymnasium framework for training language model agents on constructive tasks
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
