{% set name = "fhaviary" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhaviary-{{ version }}.tar.gz
  sha256: 625f7bbe9f1729f3ddea9e64ecb6c29653b9c6edf302d8d25be1474212472e0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.11
    - docstring_parser >=0.16
    - httpx
    - pydantic >=2.0,<3.dev0

test:
  imports:
    - aviary
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/fhaviary/
  summary: Gymnasium framework for training language model agents on constructive tasks
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
