{% set python_min = "3.11" %}
{% set name = "fhaviary" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fhaviary-{{ version }}.tar.gz
  sha256: 9d27b7b41ab740d14f11b745afc829acf097a52ada6ceed6e76660a155940714

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - docstring_parser >=0.16
    - httpx
    - pydantic >=2.0,<3.dev0

test:
  imports:
    - aviary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/fhaviary/
  summary: Gymnasium framework for training language model agents on constructive tasks
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
