schema_version: 1

context:
  python_min: "3.11"
  name: fhaviary
  version: "0.36.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fhaviary-${{ version }}.tar.gz
  sha256: eb30db4f05c94c0a29a3b55f1b0735aa3c7dbfd2e1935e162adb524e663c88fa

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - pydantic-core
    - httpx-aiohttp
    - python >=${{ python_min }}
    - docstring_parser >=0.16
    - httpx
    - pydantic >=2.0,<3.dev0

tests:
  - python:
      imports:
        - aviary
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Gymnasium framework for training language model agents on constructive tasks
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/fhaviary/

extra:
  recipe-maintainers:
    - jan-janssen
